### ISSUE TITLE
docker fails on build

### ISSUE THREAD

**Issue by dzmitryhil** [aurora-is-near/rainbow-bridge#633]
Docker fails on build

Branch: master
Revision number: fd7019ff001968105e8bb22627f5a5097ba345a8

The steps to reproduce the issue:

Run in console
```
docker-compose build --progress=plain
```

The error output:
```
#23 163.3 (node:1974) UnhandledPromiseRejectionWarning: UnsupportedProtocolError: Unsupported protocol "ws:"
#23 163.3     at normalizeArguments (/usr/src/eth2near/eth2near-block-relay/node_modules/got/dist/source/core/index.js:515:23)
#23 163.3     at got (/usr/src/eth2near/eth2near-block-relay/node_modules/got/dist/source/create.js:112:39)
#23 163.3     at Function.got.<computed> [as post] (/usr/src/eth2near/eth2near-block-relay/node_modules/got/dist/source/create.js:224:42)
#23 163.3     at getEthBlock (/usr/src/eth2near/eth2near-block-relay/eth-on-near-client.js:23:27)
#23 163.3     at EthOnNearClientContract.maybeInitialize (/usr/src/eth2near/eth2near-block-relay/eth-on-near-client.js:193:31)
#23 163.3     at processTicksAndRejections (internal/process/task_queues.js:97:5)
#23 163.3     at async execute (/usr/src/cli/init/near-contracts.js:100:5)
#23 163.3     at async Command.<anonymous> (/usr/src/utils/config/index.js:38:31)
#23 163.3     at async Promise.all (index 0)
#23 163.3     at async /usr/src/cli/index.js:913:5
```

docker versions:

Docker Compose version v2.0.1
Docker Engine - Community Version: 20.10.7

**Comment by dzmitryhil** [comment]
> @dzmitryhil let me know if using changers from #634 works for you and we can proceed to merge

Now I'm getting another one

```
#18 275.0 Deployed ETH contract to 0xc4c7497fbe1a886841a195a5d622cd60053c1376
#18 275.0 + ./cli/index.js init-near-token-factory
#18 276.8 Secret key for fungible token is not specified. Reusing master secret key.
#18 276.8 Deploying token contract.
#18 276.8 Account neartokenfactory does not exist creating it.
#18 279.4 Created account neartokenfactory
#18 281.1 Deployed contract to account neartokenfactory
#18 283.1 Adding token erc20 at 0x7cc4b1851c35959d34e635a470f6b5c43ba3c9c9
#18 284.7 Failed to initialize the token erc20 contract: Error: {"index":0}
#18 ERROR: executor failed running [/bin/sh -c sh -c "./utils/scripts/docker_prepare.sh"]: exit code: 1
------
 > [rainbow-bridge_ganache 10/10] RUN sh -c "./utils/scripts/docker_prepare.sh":
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c sh -c "./utils/scripts/docker_prepare.sh"]: exit code: 1

```
