### ISSUE TITLE
BSC: failed tests

### ISSUE THREAD

**Issue by karim-en** [aurora-is-near/rainbow-bridge#666]
Some bsc tests are failing on running `./contracts/near/eth-client/test.sh bsc`

```
./contracts/near/eth-client/test.sh bsc
   Compiling eth-types v0.1.0 (/home/karim/shard-labs/rainbow-bridge/contracts/near/eth-types)
warning: unreachable expression
   --> eth-types/src/lib.rs:305:9
    |
303 |           return BlockHeaderPreLondon::deserialize(buf).map(Into::into);
    |           ------------------------------------------------------------- any code following this expression is unreachable
304 | 
305 | /         if let Ok(header) = BlockHeaderLondon::deserialize(buf) {
306 | |             Ok(header.into())
307 | |         } else {
308 | |             BlockHeaderPreLondon::deserialize(buf).map(Into::into)
309 | |         }
    | |_________^ unreachable expression
    |
    = note: `#[warn(unreachable_code)]` on by default

warning: 1 warning emitted

   Compiling eth-client v0.1.0 (/home/karim/shard-labs/rainbow-bridge/contracts/near/eth-client)
    Finished test [unoptimized + debuginfo] target(s) in 4.65s
     Running /home/karim/shard-labs/rainbow-bridge/contracts/near/target/debug/deps/eth_client-447cbb81e5ed6ecf

running 12 tests
test tests::add_400000_block_only ... ignored
test tests::add_block_diverged_until_ethashproof_dataset_fix ... ignored
test tests::add_blocks_2_and_3 ... ignored
test tests::add_blocks_before_and_after_istanbul_fork ... ignored
test tests::add_blocks_before_and_after_nov11_2020_unannounced_fork ... ignored
test tests::add_dags_merkle_roots ... ignored
test tests::add_two_blocks_from_400000 ... ignored
test tests::add_two_blocks_from_8996776 ... ignored
Current block 10160000
Current block 10160200
test tests::bsc_add_epoch_header ... ok
Current block 10160400
thread 'tests::bsc_validate_header_12058600' panicked at 'called `Result::unwrap()` on an `Err` value: HostError(NumberOfLogsExceeded { limit: 100 })', /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/mocked_blockchain.rs:182:52
stack backtrace:
thread 'tests::bsc_update_epoch_header' panicked at 'called `Result::unwrap()` on an `Err` value: HostError(NumberOfLogsExceeded { limit: 100 })', /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/mocked_blockchain.rs:182:52
   0: rust_begin_unwind
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/result.rs:973
   4: <near_sdk::environment::mocked_blockchain::MockedBlockchain as near_sdk::environment::blockchain_interface::BlockchainInterface>::log_utf8
             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/mocked_blockchain.rs:182
   5: near_sdk::environment::env::log::{{closure}}
             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/env.rs:698
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/thread/local.rs:272
   7: std::thread::local::LocalKey<T>::with
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/thread/local.rs:248
   8: near_sdk::environment::env::log
             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/env.rs:697
   9: eth_client::EthClient::record_header
             at ./src/lib.rs:346
  10: eth_client::EthClient::add_block_header
             at ./src/lib.rs:301
  11: eth_client::tests::bsc_validate_header_12058600
             at ./src/tests.rs:571
  12: eth_client::tests::bsc_validate_header_12058600::{{closure}}
             at ./src/tests.rs:552
  13: core::ops::function::FnOnce::call_once
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/ops/function.rs:227
  14: core::ops::function::FnOnce::call_once
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/result.rs:973
   4: <near_sdk::environment::mocked_blockchain::MockedBlockchain as near_sdk::environment::blockchain_interface::test tests::bsc_validate_header_12058600 ... BlockchainInterface>::FAILEDlog_utf8

             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/mocked_blockchain.rs:182
   5: near_sdk::environment::env::log::{{closure}}
             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/env.rs:698
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/thread/local.rs:272
   7: std::thread::local::LocalKey<T>::with
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/thread/local.rs:248
   8: near_sdk::environment::env::log
             at /home/karim/.cargo/git/checkouts/near-sdk-rs-7ba52202f378a9d9/613adca/near-sdk/src/environment/env.rs:697
   9: eth_client::EthClient::record_header
             at ./src/lib.rs:346
  10: eth_client::EthClient::add_block_header
             at ./src/lib.rs:301
  11: eth_client::tests::bsc_update_epoch_header
             at ./src/tests.rs:654
  12: eth_client::tests::bsc_update_epoch_header::{{closure}}
             at ./src/tests.rs:636
  13: core::ops::function::FnOnce::call_once
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/ops/function.rs:227
  14: core::ops::function::FnOnce::call_once
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::bsc_update_epoch_header ... FAILED
Current block 10160600
Current block 10160800
Current block 10161000
Current block 10161200
Current block 10161400
Current block 10161600
Current block 10161800
Current block 10162000
Current block 10162200
Current block 10162400
Current block 10162600
Current block 10162800
Current block 10163000
Current block 10163200
Current block 10163400
Current block 10163600
Current block 10163800
Current block 10164000
Current block 10164200
Current block 10164400
Current block 10164600
Current block 10164800
Current block 10165000
test tests::bsc_validate_epoch_headers_validator ... ok

failures:

failures:
    tests::bsc_update_epoch_header
    tests::bsc_validate_header_12058600

test result: FAILED. 2 passed; 2 failed; 8 ignored; 0 measured; 0 filtered out
```

**Comment by karim-en** [comment]
@idirall22 could you please check it?

**Comment by idirall22** [comment]
@karim-en 
The error is happening because the logs exceeded 100. I fixed the issue now :)

**Comment by idirall22** [comment]
I'll open a PR
